#!/bin/sh
ssh -tt ubuntu@15.206.189.123 <<EOF
    #remove the existing temp code base
    if [[ ! -d temp_code_base ]]
    then
        rm -rf temp_code_base/
    fi
    mkdir temp_code_base
    cd ~/temp_code_base
    git clone https://github.com/abhishekwish/abhiNode.git
    cd ~/temp_code_base/abhiNode
    git checkout master
    cd ~/node-app
    rm -rf config.js module ecosystem.config.js logger.js script test package.json package-lock.json node_modules server.js
    
    cd ~/temp_code_base/abhiNode
    cp -R config.js module ecosystem.config.js logger.js script test package.json server.js cd ~/node-app
    cd ~/
    rm -rf ~/temp_code_base

    cd ~/node-app
    npm install
    npm install -g nodemon pm2
    pm2 restart ecosystem.config.js
    exit
EOF
